# Generated by Django 3.2.2 on 2021-06-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20210608_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image_fun',
        ),
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
